[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "expedition-rl"
version = "0.1.0"
description = "Expedition RL lab env"
requires-python = ">=3.9"
dependencies = ["gymnasium", "numpy"]
